services:
  saml-test-database:
    image: postgres
    restart: always
    env_file:
      -  ./.postgres.env
    ports:
      - 40001:5000
    networks:
    - saml-test
    volumes:
      - postgres:/var/lib/postgresql

  saml-test-adminer:
    image: adminer
    restart: always
    ports:
      - 40002:8080
    networks:
      - saml-test

networks:
  saml-test:
    ipam:
      config:
        - subnet: 10.20.0.0/16
volumes:
  postgres:
